openapi: 3.0.0
info:
  version: 1.0.0
  title: 3720 Class- Users API
  description: A users API for homework concepts

servers:
  - url: https://users.api/v1

security:
  - BasicAuth: []

paths:
  /users:
    get:
      description: Returns all users
      responses:
        '200':
          description: Successfully returned a list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  #  ----- Added line  --------------------------------
                  $ref: '#/components/schemas/User'
                  #  ---- /Added line  --------------------------------
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
    post:
      description: Post a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              #  ----- Added line  ------------------------------------
              $ref: '#/components/schemas/User'
              #  ---- /Added line  ------------------------------------
      responses:
        '200':
          description: Successfully created a new user
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
    patch:
      description: Update a user's type
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                    type: integer
                updateKey:
                    type: string
                updateValue:
                    type: string
      responses:
        '200':
          description: Successfully updated user
        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------

    delete:
      description: Delete a user using their unique id
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Successfully deleted a user by ID

        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------
  /users/{id}:
    get:
      description: Obtain information about a user using their unique id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: Successfully returned a user by ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  user_type:
                    type: string

        '400':
          #  ----- Added line  ----------------------------------------
          $ref: '#/components/responses/400Error'
          #  ---- /Added line  ----------------------------------------


components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic

  schemas:
    User:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        user_type:
          type: string
          enum:
            - customer
            - admin
            - business
            - CSR


  #  ----- Added lines  ----------------------------------------
  responses:
    400Error:
      description: Invalid request
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
  #  ---- /Added lines  ----
